# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03ced2deb80fbb60d6b0bc8d948764e8c585b3c7e4a74840132d97a47a174d4ea6c8b20b739749896007418e06d3f9b73158b872ba637b4ce30c20f4ec482125

test:
  secret_key_base: f48d1ce3be94eed0689af0378de41ca8916a3e8f6bb657c7b7ea31bbdc349ea9e843e6fd6448ff4e7773ed09151007c82314e5fe54ebdb260cd5d9749430f01e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
