# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7de703b045e0e009e3620697a576af63664214e49f07ccd6147d506de5ab91006025c509d4fd188e694236cf86f8708f398067b0ca510c6d9adadffe7e5404f3

test:
  secret_key_base: 6f04d65b978ca5cd3c71566b5b7e1873733d364127fa40871394418ec25fa205e9d37ce11b6010c9f93473f3180900544210b4c457095299856d98969be44d6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
