source 'https://rubygems.org'

gem 'rails', '3.2.17'

gem 'pg'

gem 'jquery-rails'

gem 'haml-rails'

gem 'bcrypt-ruby', '~> 3.0.0'

gem 'cancan'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end
