mike = Client.new("Mikael", 23)
jon = Client.new("Jon Snow", 17)
gretch = Animal.new("Gretchen", "dog")
lex = Animal.new("Alexis", "snake")
ghost = Animal.new("Ghost", "direwolf")
$fosters = Shelter.new("Foster's Home for Imaginary Friends")

$fosters.clients.push(mike)
$fosters.clients.push(jon)
$fosters.animals.push(gretch)
$fosters.animals.push(lex)
$fosters.animals.push(ghost)
