# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cb905ae2e4fd7948d1efd99ac3224ab73fa25e8216c8dc2d51695927ccc0d5123ce070141beccbcfbb2b042a52cb03fdc9712f11a61a9b5d7f4756f00d0e422

test:
  secret_key_base: fd51c9e7e3cfb1aa7a3fefafa48e7e33ff91020df11e9288d8828ba2579b3dc21cdd448ea230eaed23a97bd1787e5a4c02acf57c25ca88e34e04732868839259

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
