# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d2799e7faa231542018225f1645ed56327b7ec0b2d698e3862f716604223402c3ba2b1b067f671726c1985daeacd143381cf8188669c23b31e91181150e90f5

test:
  secret_key_base: 8a38d21f587753af5b11011fa51fb754cd09b5cc3b9637d043ade55450523069b2f832c565e03b33acf819bf314a2ec675388c2ad0b237fe4d1df731db9dd026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
