# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfa84f6154b21638fd5663fa4089fd717ff34e65d2ea45bd051cc6019743a4d1fcea1e5c99892a1870493632bc604b705df190a2cc33cc7747ed1833992190ed

test:
  secret_key_base: f83b0626bf5678acbcf7959bc1fdb4405007faa0cd9087a41bda39f6161e7f6a631fca91200bb643b074035bc7ead3f42bf92a71fbeecf2b611ec4de1bd9de97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
