# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d247535281510f5ac393c094a3b624416bbd3273f33acb80ab7a452311d70530ce3ee492a4b1e0a7e807ee51b6001da8282b207ce6da8def40f639a709c51fbb

test:
  secret_key_base: 81b65580a53afbea4cd95cb8fb144ead989f57adcbef2bbd8f8d5a372d075c5a005af1526595f36a63c0fd0cba3ac97f54dae3a3e81303002a971d306582fbfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
