# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a1ca1e52692dc0b073f7bb27b1ae5933f0092eff44dc0163e239236112463abf8974a3d0f7c19f3df77acabf3b01cff3301ce03e9e3a674cd2cf8e46eff60cb

test:
  secret_key_base: 1ece761f28e22bf17a6335a6253e75be0aca904657d58630bb0b2e3742ede264f90fe0198ff0c0f6b48bfe3c7c6bb05d8c2fb42c768d98166aeea3e0943e5c92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
