# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5482603b9c31e51d51138e0c9bc9979f341fe23aff11590f16ee93b2d16149464be017b6629d1d23a8ae3c649f497ff61462df35f2ce06814fb0a1b180b05ea

test:
  secret_key_base: 5cec059dad46c807d680a1b2ed363cf206978e2e590a8fafbf7dbf105ddc76814db0e6f1cfb0e7f765248219d3467870b93df857bf17c54ac5d5b9a9c416d273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
