# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9e149aa58caaa9c2149b99831937f9cf6e15413acdabb817a31dc89efd12c7e602aef4e77bd159f319bbc200711003488f538260ac9f190f4718ee503618e2e

test:
  secret_key_base: 6027ed7ac89976042537c95a266372f4fac76f3d978ba4f4278b4e356669dd3dba7ec83a18e3f8788b06edfdf1ae159680f49b1c24bd8a1be007615d14a61271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
