# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ae6e105910e75e4ce5091abfd5434548dfad8d7fba872dee853250e84365c824a91db3f04d95e36c72a0dbcd1780beaa852388b153289c73fc814e767912bd

test:
  secret_key_base: 2daf2ee9ad3561ac25e20e75f643c3307be2800c1fbbbee174acf8783a21294873d2a1857febafae9d0fb17a7e788d40a922fce3feda9a58b2dcab5bf50ba8f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
