require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RappersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Rapper. As you add validations to Rapper, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RappersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rappers as @rappers" do
      rapper = Rapper.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rappers)).to eq([rapper])
    end
  end

  describe "GET show" do
    it "assigns the requested rapper as @rapper" do
      rapper = Rapper.create! valid_attributes
      get :show, {:id => rapper.to_param}, valid_session
      expect(assigns(:rapper)).to eq(rapper)
    end
  end

  describe "GET new" do
    it "assigns a new rapper as @rapper" do
      get :new, {}, valid_session
      expect(assigns(:rapper)).to be_a_new(Rapper)
    end
  end

  describe "GET edit" do
    it "assigns the requested rapper as @rapper" do
      rapper = Rapper.create! valid_attributes
      get :edit, {:id => rapper.to_param}, valid_session
      expect(assigns(:rapper)).to eq(rapper)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rapper" do
        expect {
          post :create, {:rapper => valid_attributes}, valid_session
        }.to change(Rapper, :count).by(1)
      end

      it "assigns a newly created rapper as @rapper" do
        post :create, {:rapper => valid_attributes}, valid_session
        expect(assigns(:rapper)).to be_a(Rapper)
        expect(assigns(:rapper)).to be_persisted
      end

      it "redirects to the created rapper" do
        post :create, {:rapper => valid_attributes}, valid_session
        expect(response).to redirect_to(Rapper.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rapper as @rapper" do
        post :create, {:rapper => invalid_attributes}, valid_session
        expect(assigns(:rapper)).to be_a_new(Rapper)
      end

      it "re-renders the 'new' template" do
        post :create, {:rapper => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rapper" do
        rapper = Rapper.create! valid_attributes
        put :update, {:id => rapper.to_param, :rapper => new_attributes}, valid_session
        rapper.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested rapper as @rapper" do
        rapper = Rapper.create! valid_attributes
        put :update, {:id => rapper.to_param, :rapper => valid_attributes}, valid_session
        expect(assigns(:rapper)).to eq(rapper)
      end

      it "redirects to the rapper" do
        rapper = Rapper.create! valid_attributes
        put :update, {:id => rapper.to_param, :rapper => valid_attributes}, valid_session
        expect(response).to redirect_to(rapper)
      end
    end

    describe "with invalid params" do
      it "assigns the rapper as @rapper" do
        rapper = Rapper.create! valid_attributes
        put :update, {:id => rapper.to_param, :rapper => invalid_attributes}, valid_session
        expect(assigns(:rapper)).to eq(rapper)
      end

      it "re-renders the 'edit' template" do
        rapper = Rapper.create! valid_attributes
        put :update, {:id => rapper.to_param, :rapper => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rapper" do
      rapper = Rapper.create! valid_attributes
      expect {
        delete :destroy, {:id => rapper.to_param}, valid_session
      }.to change(Rapper, :count).by(-1)
    end

    it "redirects to the rappers list" do
      rapper = Rapper.create! valid_attributes
      delete :destroy, {:id => rapper.to_param}, valid_session
      expect(response).to redirect_to(rappers_url)
    end
  end

end
