# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 009352da8237ffb1ca499eff74fab5b847e82de5f700f8c88a1f8493426e5eba600c983580c1a1f08a0cbeaae5065f07bc6f3811ff91412bbe5944029f66baeb

test:
  secret_key_base: 7c702d78845216cd3e656c6ad0b59d642f6920644807097ae799e1e27d48bcadc6792bb01736ac18b048b2db48fc309d6eb0a9b1e33c30e8d848f568745cb56b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
