# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88e54f00871fd2431d51fd329c90b75ff7623ef0a06b1bb9251654561e90d497f4f1d850e262511bb0bf5c7923ef806ac2fbb6bda6bc1c3e9b28040fc968c31c

test:
  secret_key_base: 59bbba0b9388ab693dcd6f9ec6e63f64abb6c67b330a0ccd956ff9eafe40cba690aa1e85b274e467f1dfb5e8a7299479f5ec4a9f369497234814f9eee5fe1b43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
