# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a49b7db560c14ebe978b7f45f53ad6d6bdcdd9beda67e2878fc10810edd36c87874697ea0a53c76a6a0403adac0a15cb18699aca6f5581ff5dcb1f78e1f2d8b9

test:
  secret_key_base: 151e46d2d0c3deb867cab2cbc535e5c62abcc8093cb57f469458df0a3cf45012d06b46cd6b050ae1a3c1940c323ff88a0d6418b404435bd870264bdaa33393ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
