# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 340f1cd56b101bf57438a1a3720f27cd4f90e7c2d529854290046e477409978c386648dedd080c8e8b0937f9c0be8dcc5edb53f6b8d556ec0a3dcd7bd76b9a9a

test:
  secret_key_base: ad5b314740f73930e3f1b903bf0155517e5329cec285291f5efcf47002fa3b00b8cac7e3a28c8ddedf93c761c5b0d9a2253cd2e3e0f96dd3607e61c2692bff06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
