# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c921615007d7b0809364a2bf181e8823b125020aa2bd03abec13710f732232669706bea3f4a14ca9918a07eef2587e655d861efade0a48f903039088493aa4fe

test:
  secret_key_base: 6aaacf528d2ebf9aaf5e1ee5e527bfdb352c12cda67cf8a0fc70852a29675c90a8cb667324aee2ed3afcac10ea131f06360e7f76fa744990057df42f53b6fd4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
