# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b975fb797aeb879dc9ee6de71346ed9d61c390f841737442c22c9b0014a7bdde33a64708480c0e0ed98a1e288a102c7176eae315b10c7f327c0385ab26d9185f

test:
  secret_key_base: 074889231604b2ff9f9140dcf09e773d769012448abf74a35f4244655a11b94a220bc920bd3dba7c517200d977b507d7f8cb0b727bf58a2a158ba9ba1761c404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
