source "https://rubygems.org"

gem "rails", "4.1.1"
gem "pg"
gem "sass-rails", "~> 4.0.3"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.0.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "bcrypt", "~> 3.1.7"

group :doc do
  gem "sdoc", "~> 0.4.0"
end

group :development, :test do
  gem "spring"
  gem "pry-rails"
  gem "rspec-rails"
  gem "awesome_print"
  gem "shoulda-matchers"
  gem "capybara"
  gem "launchy"
  gem "nyan-cat-formatter"
end
