# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 003585a253063c573bddfab63055c3a3201ba885431c5caf7a205d1690a747019ecf074c1c3f2b74012e5edb872511425f6a10be8b262e4b04fad32f6df7f2fe

test:
  secret_key_base: 8b40c5e6d4663afcfaa7af9d64969f9791a75a7fa82467d0bfcb045c54ab1f8a3d1a5551c0b77403cbe41863fd0aa7d1117bedad3beece88b55692fc806ab1b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
