# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33da2e7e35b60856d1e778da0049100749a936a8df9b35ce8b7306092943dd8f1f896f4464fb06e8214531b4da57141dfa7616fe2385a13761c44729d126e867

test:
  secret_key_base: 44f6c1f77306cca15621bee4a79f530c4b521c7668619d0e52ce869f704781d23e40efdcdba64a542169539333a9c708e1b348465c391dcb49d5c4c0f63b4df7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
