# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd94080113a0c3d47b999215ff04ff0baa7386a665d37af159c47dc81953fe8dd2d5e72a2c8063a3bd86978e213688647d37d262b3a08582c4f7be9e4d36caf

test:
  secret_key_base: 067e79f21513f0e0f78c32f994ef57be53a586f08b01099b43c652e748502a9320ee2ad21610e1e6c910d0a666f4242799315f0b4b031f5a2d8af34aa9fae81a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
