# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b65cfb3f8704f302a80e26e0c0be282349f80f874986622c8da1aa4e9dab8a8f3e5e7521e0d0274e4466e186b1dc163f13ff5884e2da73a3705fa76b247c04e

test:
  secret_key_base: 21283d2348cd8525deb89fa455f2663cef47c2b05589f1b764f472d76c78738ec2ea24cace893a4392c613a86efe3ae649767ff857c67ec7cb82d84d625ed3c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
