# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 797cf162d6d3833664a74653cfbd2365f840d345145fe0b76ba33bdcaf2debf560f316a504fe285a7400cfd6163e758aa0f11c4dd5fdf7a758865c6334c024e4

test:
  secret_key_base: 3d712e334b574236460369e949e59476800dded2b1b870424b374ba52cedadaa1be82bda108e4793b07fa3ab7b8163ff152eba1016fb025d9b7b483fa177c53a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
