# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ffcbcfdbf103afe4008b1c9b5c6efb194eb0326806bba9591481724474118a1b190e7603e75dd150a95b6335917ffe2a2aeb658ff0fd896830d6d9067191246

test:
  secret_key_base: 61d127725e3d2df0b1d9cfbb46ef07adb8d11b3d7d9470faf7d0b00cc314b2f10ecf6a7c0cdd8f59e20e6527036cbc5476ec1a4342895da4935e5c847f316e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
