# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19c7039a3de1ad7f83024a3e61932a1c2819afa57933167e9fd6ba1b5f357311d31903248bbda8489dc7eab89b67288992acc8473e8e36b933d27ef2b355111f

test:
  secret_key_base: 21dab5dfa0719eccb586e890d611ddcaad86659658e3593af71748eeaadd84a923022804acf1b1d00e089d1c30a963538ab29e5945c3f5029464ea9b2350aff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
