# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f44cbadafad46e03a38002521375bc91f00082a269557842ac0dd17db9be33a57427b6b851849a8222c7eb5adc00a95a8020d3972756a0bca2f489f18148d61

test:
  secret_key_base: f287999cde467633b31639c32124a023f9c0d1638abceb3affcc68211d318fcd96bb05edcdb1747cf98502d468d805f898b1f891a2b0603dedd9178878637011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
