# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f18592eb5e965cb98162cc27de16163e33f3068a1d2af1a78d42930460311d4d5942a32469b0869af13ac3f646b8ef6e4bbc42b1834babfe95b8464a008d1200

test:
  secret_key_base: dd977fa5fa032d005c4f5fc48031fc68e350ff02816ebdb3c4becad093c52240e126c69d897c9f8fd6222b278cac93add8c27ca8329568b1d8930c7d2135f3ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
