// Generated by CoffeeScript 1.8.0
(function() {
  ￼class(SelectFlights({
    constructor: function(fetchingFlights) {
      this.fetchingFlights = fetchingFlights != null ? fetchingFlights : null;
      $("#tabs ul li a").bind({
        click: this.changeTab
      });
      return $("#tabs #error a").click((function(_this) {
        return function(event) {
          event.preventDefault();
          return _this.showFlights($("#tabs li a.active").attr("href"));
        };
      })(this));
    },
    showFlights: function(activeDiv) {},
    changeTab: (function(_this) {
      return function(event) {};
    })(this)
  }));

}).call(this);
