# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ff2f7a73e76dcb34ef9e439549919fa10b6a331ecec03d594983f03faefa44dde3868103c455e9e22b24312fe234ef9851652e0267a327c700ceeb51d33f2e

test:
  secret_key_base: 901ea81521eb4e28b841cc180e53158006fc671d4df1752100c89481275b1562c77f0a02ddb55ba9ae6a24f0b856fe2b90469abb90636e2350ef6a75dae0b3f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
