# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ccb65cbd1c7fb0c1c29b69774f8b9c14e4c9c32c368b4c81e2387f1103506f2d37b28282979fdbb31f2c6f9f5ae56e5d0f2ab8962bda5daf759ba2f8f638136

test:
  secret_key_base: ff1055d954e173abda26368f59c973ee0e9bbcd60ed73196fcc9214b9ea71a8c340ef5d155ba8f547d5215de5522aec5508468df52ecad7ce5f1b99d8b15b4ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
