# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75c6717e0bd5f3855d67939fc866007e27cfbe077905bd90985c0b34ceb30728cafc826649a64302939bbd477445681b90a1cd53945887ac17c9c1fd27693fd9

test:
  secret_key_base: 1a2471034f69a95d8e5d53569a24e587200a0afbca6b9e2dbb73fcb181e5b32ea0bf748ae66db184d55205b39d85eeefb74fa3f05bc65e2587534aa265ee4377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
