# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2ee107ecc4dd907d7962b9a7dade629c5fad04f7a58fdfe2228350f544eb87fb361b5bb1b26cdb3b6b8b1a5a5e46d0eb5b4ba158741467d26abba6690a71705

test:
  secret_key_base: d03c3e62de6bc3fb5a4ddb53a3614b16b2045a8afeac33a1a2b57bda0471ab0d936e298dd97247df76fd0a2aa9095db72fceccff6ea3f70e09148e459fb492f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
